### ISSUE TITLE
Why Java 32-Bit?

### ISSUE THREAD

**Issue by RaiMan** [clarkburbidge/SikuliCalc#1]
Hi, this is RaiMan from http://sikulix.com.

Why do you recommend to use a Java 32-Bit version?

Neither SikuliX nor Jython require a Java 32-Bit version when running on a 64-Bit system.

IMHO: if ever possible, one should only have the latest Java version on the machine (JRE or JDK or both depending on usage situation) and always as 64-Bit only if the system is 64-Bit.

The need to use a Java 32-Bit version only arises, if you use a Java application, that contains native libraries only available as 32-Bit (which was the case for example with Sikuli prior to version 1.0.1).

**Comment by clarkburbidge** [comment]
There was some instruction on one of the install tutorials for Robot Framework that specified that "everything" be in 32 bit, though now that I think about it I think it was for RIDE, which I have mostly abandoned for PyCharm and command line. I didn't know where to stop and once it was working that was the versions were no longer important to me. I'll switch to the 64 bit Java and make a change in the README. 

My reasoning with this repository was to try and get some of this sorted out and made clear because I am still a bit confused and mostly found older tutorials. As things have changed (Windows 8.1 SikuliX 1.1.0, etc.), it seems that there is a need for this discussion in the Robot Framework with Remote SikuliX Library arena. 

Thanks for your input and the amazing work with SikuliX!!

**Comment by RaiMan** [comment]
Thanks for feedback.

Just started on Mac 10.10, to get things running principally along the road you have documented.

My testcase is https://github.com/rtomac/robotframework-selenium2library, which has a rather demanding demoapplication.

My current goal is, to find a setup, that allows, to  prepare everything in a Jython 2.7.0 environment and then be able, to run RFW tests from a SikuliX script.
The mentioned demo app already works, the RFW test output is produced, but the tests are still failing ;-)

The next days I will repeat that on Windows.

**Comment by RaiMan** [comment]
basic RFW support is available since version 1.1.3
